Handle alternative phrasings
StampyAI/stampy-nlp pull request #22
Opened 2023-05-17 18:13 UTC by mruwnik

https://github.com/StampyAI/stampy-nlp/issues/13

2023-05-17 18:14 UTC, mruwnik commented on src/stampy_nlp/utilities/coda_utils.py
> +    while response:
coda will not return more than 500 items - to get more the results have to be paginated :/

2023-05-17 19:06 UTC, ccstan99 reviewed
One potential hiccup doing it this way, we may be treating the alternate phrase on "equal footing" with the actual / original question, i.e. when the results are returned, it may not be clear what was the original title of the question and which are alternatives. I don't know if this'll be an issue. Do we need/want an additional field to keep track?

Also, just doing a quick check on a several alternate phrasing, the python sentence transformer already pulls them as most similar. Maybe the tensorflow is less accurate but still in the top 5 on several.

Finally, I'll want to test this out before approving, but I probably won't have time to do it properly until the weekend.

2023-05-17 19:07 UTC, mruwnik commented on src/stampy_nlp/utilities/coda_utils.py
> +    while response:
I was getting back 500 results. Which is a suspiciously round number :D

2023-05-20 20:22 UTC, ccstan99 requested changes
Unfortunately, the NLP endpoint doesn't work since the alternate phrases are using the same id which must be unique in pinecone. We should probably use a hash value or something instead of using the coda id. Of course, the deduplication will need to filter by something else, like paged since the id will no longer match.

2023-05-21 21:16 UTC, mruwnik commented on src/stampy_nlp/utilities/coda_utils.py
> +                    'id': f'{item["id"]}{i or ""}',
a bit of magic here to make sure that the ids are unique. This has the nice effect of leaving the prexisting values in the index as are, and adding new ids for alternative phrasings

2023-05-22 08:25 UTC, ccstan99 approved these changes
Great! Your "magic" is a better way to preserve the existing id. I was going to suggest it after reading your earlier discord message but of course, you beat me to it. 

Since pageid is stored in pinecone metadata, the deduplication needs to check `result['metadata']['pageid']` not since `result['pageid']` isn't a valid field. I made a commit with that change.

Both pinecone and tensorflow's json now include the embeddings for the alternate phrasings in their deployed versions. However, I think something might still be off with the pinecone embeddings. There were originally 439 questions + 28 alternate phrasings so we should have 467 but there's 745 now. It doesn't seem to cause any obvious problems but needs to be further investigated. Unfortunately, I'm swamped preparing for a couple of presentations for Wednesday and Thursday.

In the meantime, feel free to merge this and the stampy-ui deduplication PR whenever you're comfortable.

2023-05-22 08:54 UTC, mruwnik commented
That actually makes sense, since there are some 720 answers returned when pagination  is used

2023-05-22 08:54 UTC, merged